//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARK6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Event_start { get; set; }
        public string Event_end { get; set; }
        public Nullable<bool> All_day { get; set; }
        public int Event_id { get; set; }
    }
}
