//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARK6.Models
{
    using System;
    using System.Collections.Generic;
	using System.Web;

	public partial class MediaGallery
    {
        public int MediaId { get; set; }
        public string Title { get; set; }
        public string MediaPath { get; set; }
        public string MediaType { get; set; }

        public HttpPostedFileBase MediaFile { get; set; }
    }
}
